const GATEWAY_SERVER = process.env.NEXT_PUBLIC_GATEWAY_SERVER;

export const INCOME_SERVER = GATEWAY_SERVER + "/api/v1"

export const DOCUMENT_ENTITY = '/documents'

export const CASE_ENTITY = '/cases'

export const NOTIFICATION_ENTITY = '/notifications'

// https://github.com/LBHackney-IT/lbh-income-api/blob/edb968e0a65f7d29d7cff5695e1400bea39b6191/lib/hackney/tenancy/action_codes.rb
export const ACTION_CODE_DICT = {
    'GAT': 'AUTOMATED_SMS_ACTION_CODE',
    'GAE': 'AUTOMATED_EMAIL_ACTION_CODE',
    'GMS': 'MANUAL_SMS_ACTION_CODE',
    'GME': 'MANUAL_EMAIL_ACTION_CODE',
    // Identical?
    // 'GMS': 'MANUAL_GREEN_SMS_ACTION_CODE',
    'AMS': 'MANUAL_AMBER_SMS_ACTION_CODE',
    'VFL': 'LETTER_FAILED_VALIDATION_CODE',
    // Codes for letters as follows:
    'LF1': 'LETTER_1_IN_ARREARS_FH',
    'LF2': 'LETTER_2_IN_ARREARS_FH',
    'LL1': 'LETTER_1_IN_ARREARS_LH',
    'LL2': 'LETTER_2_IN_ARREARS_LH',
    'LS1': 'LETTER_1_IN_ARREARS_SO',
    'LS2': 'LETTER_2_IN_ARREARS_SO',
    'IC1': 'INCOME_COLLECTION_LETTER_1',
    'S01': 'INCOME_COLLECTION_LETTER_1_UH',

    'IC2': 'INCOME_COLLECTION_LETTER_2',
    'S02': 'INCOME_COLLECTION_LETTER_2_UH',
    'ZR2': 'INCOME_COLLECTION_LETTER_2_UH_ALT',
    'ZL2': 'INCOME_COLLECTION_LETTER_2_UH_ALT_2',
    'ZT2': 'INCOME_COLLECTION_LETTER_2_UH_ALT_3',

    'IC3': 'PRE_NOSP_WARNING_LETTER_SENT',
    'IC4': 'COURT_WARNING_LETTER_SENT',

    'CBL': 'COURT_BREACH_LETTER_SENT',
    'BLI': 'INFORMAL_BREACH_LETTER_SENT',
    'AGR': 'AGREEMENT_BROUGHT_UP_TO_DATE',
    
    'IAC': 'INFORMAL_AGREEMENT_CONFIRMATION_LETTER',
    //Duplicated as well?
    // 'BLI': 'INFORMAL_AGREEMENT_BREACH_LETTER',

    'CDL': 'COURT_DATE_LETTER',
    
    'FAC': 'FORMAL_AGREEMENT_CONFIRMATION_LETTER',
    // Duplicated as well?
    // 'CBL': 'FORMAL_AGREEMENT_BREACH_LETTER',

    'C': 'FIRST_FTA_LETTER_SENT',
    'MML': 'ARREARS_MAIL_MERGE_LETTER_SENT',
    'S0A': 'S0A_ALTERNATIVE_LETTER',
    'REF': 'FTA_REFUND_REQUEST_LETTER_SENT',
    'ZW1': 'MW_LETTER_ACTION_1_COMPLETED',
    'ZW2': 'MW_LETTER_ACTION_2_COMPLETED',
    'ZW3': 'MW_LBA_LETTER_COMPLETED',
    'MW1': 'MW_LETTER_ACTION_1',
    'MW2': 'MW_LETTER_ACTION_2',
    'MW3': 'MW_LBA_LETTER',
    'SMS': 'TEXT_MESSAGE_SENT',
    'ZR1': 'STAGE_ONE_COMPLETE',
    'ZR3': 'STAGE_THREE_COMPLETE',

    'VIM': 'VISIT_MADE',
    'CBV': 'COURT_BREACH_VISIT_MADE',
    
    'WPA': 'WARRANT_OF_POSSESSION',

    'RMD': 'PAUSED_MISSING_DATA',

    'CVB': 'C19_COURT_ORDER_BREACHED',
    // ADJOURNED_GENERALLY = Hackney::Tenancy::OldCourtOutcomeCodes::ADJOURNED_GENERALLY
    'AGE': 'ADJOURNED_GENERALLY',
    // ADJOURNED_ON_TERMS = Hackney::Tenancy::OldCourtOutcomeCodes::ADJOURNED_ON_TERMS
    'ADT': 'ADJOURNED_ON_TERMS ',
    //end 

    'CAP': 'CHARGE_AGAINST_PROPERTY',
    'CAW': 'COSTS_AWARDED',
    // Duplicated as well?
    // 'CBL': 'COURT_BREACH_LETTER',

    'IC5': 'COURT_OUTCOME_LETTER',
    // Duplicated as well?
    // 'IC4': 'COURT_WARNING_LETTER',
    'CDS': 'COURT_DATE_SET',
    'DPQ': 'DWP_DIRECT_PAYMENTS_REQUESTED',
    'DEC': 'DECEASED',
    'MBH': 'DELAYED_BENEFIT',
    'DDC': 'DIRECT_DEBIT_CANCELLED',
    'EVI': 'EVICTION',
    'EDS': 'EVICTION_DATE_SET',
    'FIC': 'FINANCIAL_INCLUSION_CALL',
    'FIO': 'FINANCIAL_INCLUSION_INTERVIEW',
    'FIV': 'FINANCIAL_INCLUSION_VISIT',
    'MHB': 'HB_INVESTIGATION_PENDING',
    'HBO': 'HB_OUTSTANDING',
    'INC': 'INCOMING_TELEPHONE_CALL',
    'MJA': 'MONEY_JUDGEMENT_AWARDED',
    'NTS': 'NOTICE_SERVED',
    'NTC': 'NOTICE_CANCELLED',
    'OFI': 'OFFICE_INTERVIEW',
    'OOC': 'OUT_OF_HOURS_CALL',
    'OTC': 'OUTGOING_TELEPHONE_CALL',
    // POSTPONED_POSSESSION = Hackney::Tenancy::OldCourtOutcomeCodes::POSTPONED_POSSESSION
    'PPO': 'POSTPONED_POSSESSION',
    //end 
    'POP': 'PROMISE_OF_PAYMENT',
    'DEB': 'REFERRED_FOR_DEBT_ADVICE',
    // SUSPENDED_POSSESSION = Hackney::Tenancy::OldCourtOutcomeCodes::SUSPENDED_POSSESSION
    'SUP': 'SUSPENDED_POSSESSION',
    //end
    'UCC': 'UNIVERSAL_CREDIT',
    'VIU': 'UNSUCCESSFUL_VISIT'
}

export type CaseActionCode = keyof typeof ACTION_CODE_DICT;

export const ACTION_CODE_UI_TEXT_DICT = {
    'CVD': 'Covid 19 Call',
    'CVB': 'C19 Court Order Breached',
    'CBV': "Court Breach Visit Made",
    'Z00': "Arrears Cleared",
    "1RS": "Old Stage One",
    "2RS": "Old Stage Two",
    "AGR": "Agreement brought up-to-date",
    "3RS": "Old Stage Three",
    "4RS": "Old Stage Four",
    "RR4": "Reset Stage Four",
    "ZR1": "Stage One Complete",
    "ZR2": "Stage Two Complete",
    "ZR3": "Stage Three Complete",
    "ZL4": 'Legal Referral Complete',
    "1TS": 'Stage One (T)',
    '2TS': 'Stage Two (T)',
    '5TA': 'Eviction',
    'ZT4': 'Court Proceedings Complete',
    'ZT5': 'Eviction Complete',
    'ZR5': 'Pre-Court Complete',
    '0RA': 'Old Breached Agreement (0)',
    '5RP': 'Pre Court',
    '4TC': 'Court Proceedings',
    'ZR4': 'Stage Four Complete',
    'ZT1': 'Stage One Complete',
    '1RA': 'Old Breached Agreement (1)',
    '2RA': 'Old Breached Agreement (2)',
    '3RA': 'Old Breached Agreement (3)',
    '6RO': 'Breached Order',
    '1LA': 'Breached Agreement 1L',
    '1LS': 'Stage One (L)',
    'ZT2': 'Stage Two Complete',
    '2LS': 'Stage Two (L)',
    'GEN': 'General Diary Note',
    '3LS': 'Stage Three (L)',
    '4LL': 'Legal Referral',
    '0LA': 'Breached Agreement 0L',
    '3LA': 'Breached Agreement 3L',
    '2LA': 'Breached Agreement 2L',
    '4LA': 'Breached Agreement 4L',
    'ZL1': 'Stage One Complete',
    'ZL2': 'Stage Two Complete',
    'ZL3': 'Stage Three Complete',
    'ZR6': 'Court Proceedings Complete',
    'CDL': 'Court Date Letter',
    'IC6': 'Court Outcome Added',
    'IC5': 'Court Outcome Letter',
    'IC4': 'Court Warning Letter',
    '3TS': 'Stage Three (T)',
    'BRE': 'Breached Agreement',
    'ZT3': 'Stage Three Complete',
    'OUT': 'Outright Possession Order',
    'VIU': 'Unsuccessful Visit',
    'VIM': 'Visit Made',
    'CAW': 'Costs Awarded',
    'ZT6': 'Eviction Complete',
    'MJA': 'Money Judgement Awarded',
    'CAP': 'Charge Against Property',
    'SPO': 'Suspended Possession',
    'PPO': 'Postponed Possession',
    'ADG': 'Adjourned Generally',
    'ADT': 'Adjourned on Terms',
    'DPQ': 'DWP Direct Payments Requested',
    'HBO': 'HB Outstanding',
    'DPR': 'DWP Direct Payments Refused',
    'DPM': 'DWP Direct Payments Being Made',
    'DPT': 'DWP Direct Payments Terminated',
    'MJQ': 'Money Judgement Requested',
    'EVI': 'Eviction',
    'DIS': 'Dispute',
    'CRC': 'Complaint Received',
    'CRS': 'Complaint Resolved',
    'NTS': 'Notice Served',
    'NTC': 'Notice Cancelled',
    'ITS': 'Introductory Tenancy to Secure',
    'VAP': 'Voluntary Attach. of Earnings',
    'IPA': 'Involuntary Att. of Earnings',
    'WEA': 'Warrant of Exec. Applied for',
    'NES': 'Notice of Extension Served',
    '7RE': 'Eviction',
    '1TA': 'Breached Agreement (1)',
    'DA1': 'Referred to Moorcroft',
    'DDR': 'Direct Debit new sign up',
    'DDC': 'Direct Debit Cancelled',
    'FTA': 'Now a Former Tenants Account',
    'AGG': 'FTA ARREARS AGREEMENT',
    'CDD': 'Changes to DirectDebit payment',
    'DC1':  'First contact with NOK',
    'DC2': 'Subsequent contact with NOK',
    '2TA': 'Breached Agreement (2)',
    'RT1': 'Returned by Moorcroft',
    'C': 'First FTA letter sent',
    'D': 'Second FTA reminder',
    'E': 'FTA Debt Agency warning',
    'FIV': 'Financial Inclusion Visit',
    'FIC': 'Financial Inclusion Call',
    'FIO': 'Financial Inclusion Interview',
    'OOC': 'Out of hours call',
    '3TA': 'Breached Agreement (3)',
    'OFT': 'Office interview',
    'DDP': 'Direct Debit Payment',
    'BA': 'FTA Broken Agreement',
    'S01': 'S01 Stage One',
    'S02': 'S02 Stage Two',
    'S03': 'S03 Stage Three',
    'S04': 'S04 Stage Four',
    'S05': 'S05 Court',
    'S06': 'S06 Breach Court Order',
    'S0A': 'S0A Alternative Letter',
    '6RC': 'Court Proceedings',
    'CBL': 'Court Breach Letter',
    'WOA': 'Write Off - Uneconomical',
    'WOB': 'Write Off - Vulnerable/Infirm',
    'WOC': 'Write Off - Deceased',
    'WOE': 'Write Off - Address Unknown',
    'WOF': 'Write Off - Dispute unresolved',
    'WOH': 'Write Off - All action failed',
    'WOD': 'Write Off - FT on Prison',
    'VUN': 'Vunerable',
    'ZR7': 'Eviction Complete',
    'DEB': 'Referred for debt advice',
    'REP': 'Repairs',
    'PAB': 'Possible abandonment',
    'TMO': 'TMO a/c - no action required',
    'REF': 'FTA Refund Request Letter Sent',
    'MML': 'Arrears mail merge letter sent',
    'UCC': 'Universal Credit',
    'SMS': 'Text message sent',
    'ACB': 'Actual Cost Breakdown Sent',
    'TAA': 'TA New Account checks',
    'RAP': 'Outcome of rent arrears panel',
    'PLA': 'Pre legal action visit',
    'PEO': 'Pre eviction contact outcome',
    'AAD': 'Pre notice interview',
    // 'RAP': 'Rent Arrears Panel Outcome',
    'DA4': 'Referred to Credit Gee',
    'RT4': 'Returned by Credit Gee',
    'ZW0': 'MW Pre Arrears Completed',
    'ZW1': 'MW Letter Action 1 Completed',
    'ZW2': 'MW Letter Action 2 Completed',
    'ZW3': 'MW LBA Letter Completed',
    'ZWD': 'MW Charges Disputed Completed',
    'ZWC': 'MW MCOL Completed',
    'ZWL': 'MW Legal Referral Completed',
    'ZWA': 'MW Arrangement Completed',
    'AWO': 'Write on - arrears reinstated',
    'MWB': 'MW Arrangement Breached',
    'NFA': 'FTA - TO BE TRACED',
    'INC': 'Incoming telephone call',
    'OTC': 'Outgoing telephone call',
    'DA2': 'REFERRED TO VIL COLLECTIONS',
    'DA3': 'REFERRED TO LEWIS DEBT AGENCY',
    'RT2': 'RETURNED BY VIL COLLECTIONS',
    'RT3': 'RETURNED BY LEWIS DEBT AGENCY',
    'INV': 'ACTION ON HOLD',
    'MHB': 'HB INVESTIGATION PENDING',
    // 'RT4': 'Returned by Credit Gee',
    'MW0': 'MW Pre Arrears',
    'MW1': 'MW Letter Action 1',
    'MW2': 'MW Letter Action 2',
    'MW3': 'MW LBA Letter',
    'MWD': 'MW Charges Disputed',
    'MWC': 'MW MCOL',
    'MWL': 'MW Legal Referral',
    'MWA': 'MW Arrangement',
    'WON': 'Arrears reinstated to offset',
    'GAT': 'Automated green in Arrears sms message',
    'GAE': 'Automated green in Arrears email message',
    'GME': 'Manual green in Arrears email message',
    'GMS': 'Manual green in Arrears sms message',
    'AMS': 'Manual amber in Arrears sms message',
    'CDS': 'Court date set',
    'EDS': 'Eviction date set',
    'POP': 'Promise of payment',
    'DEC': 'Deceased',
    'MBH': 'Delayed benefit',
    'LF1': 'Letter 1 in arrears FH',
    'LF2': 'Letter 2 in arrears FH',
    'LL1': 'Letter 1 in arrears LH',
    'LL2': 'Letter 2 in arrears LH',
    'LS1': 'Letter 1 in arrears SO',
    'LS2': 'Letter 2 in arrears SO',
    'SLB': 'Letter Before Action',
    'IC1': 'Income Collection Letter 1',
    'IC2': 'Income Collection Letter 2',
    'RMD': 'Missing Data',
    'WPA': 'Warrant of Possession',
    'BLI': 'Informal Agreement Breach Letter Sent'
}

export const COURT_OUTCOME_CODE_DICT = {
    'AGP': 'Adjourned generally with permission to restore',
    'AND': 'Adjourned to next open date',
    'AAH': 'Adjourned to another hearing date',
    'ADH': 'Adjourned for directions hearing',
    'ADT': 'Adjourned on terms',
    'OPF': 'Outright possession forthwith',
    'OPD': 'Outright possession with date',
    'SOT': 'Suspension on terms',
    'STO': 'Struck out',
    'WIT': 'Withdrawn on the day',
    'SOE': 'Stay of execution'
}

export type CaseCourtOutcome = keyof typeof COURT_OUTCOME_CODE_DICT
